# Generated by Django 5.1.5 on 2025-01-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
