# Generated by Django 5.1.5 on 2025-02-05 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_post_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aigeneration",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "AI 생성 이미지",
                "verbose_name_plural": "AI 생성 이미지들",
            },
        ),
    ]
