# Generated by Django 5.1.5 on 2025-02-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_aigeneration_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
