# Generated by Django 5.1.5 on 2025-02-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="generated_prompt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
