# Generated by Django 5.1.5 on 2025-02-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_post_generated_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
