# Generated by Django 5.1.5 on 2025-02-06 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_post_is_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tag_set",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
