# Generated by Django 5.1.5 on 2025-01-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
