# Generated by Django 5.1.5 on 2025-02-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_playground", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiimagegeneration",
            name="image_url",
            field=models.URLField(max_length=1000),
        ),
    ]
